### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ghost** [aradianoff/recatpchacontact#9] opened 2015-10-14 19:33 UTC
Error after latest update. See attachment screenshot.
![screen shot 2015-10-14 at 2 29 01 pm](https://cloud.githubusercontent.com/assets/5008228/10495240/738829d8-7280-11e5-8fc7-26be103d8dce.png)

**Comment by aradianoff** [comment] 2015-10-15 16:20
Can you check if it works now with the new 1.0.8 release just to make sure?

**Comment by ghost** [comment] 2015-10-16 01:05
Just tried v1.0.8 ... same results.

**Comment by bassplayer7** [comment] 2015-10-16 15:07
@umbergerba, could you provide a rough overview of your setup, so I can try to duplicate your issue?

**Comment by ghost** [comment] 2015-10-24 17:41
I've combined the Antimatter One-Page template with the Antimatter Blog template. Also, I'm using theme inheritance by creating a Child-Theme based upon Antimatter. You can view the site here ... http://mettle-endeavors.com ... let me what else you might need.

In addition, I tried removing the plugin completely and reinstalled it from scratch, but got the same error still. THX!

Brian U.

**Comment by ghost** [comment] 2015-10-24 17:43
Also, I've just updated to GRAV 1.0 RC1 and all other plugin are updated too.

**Comment by bassplayer7** [comment] 2015-10-24 17:49
Great. Thanks for the details. I'll see if I can get some time to look into the problem. 

On Saturday, Oct 24, 2015 at 12:43 PM, B.A. Umberger notifications@github.com, wrote:

Also, I've just updated to GRAV 1.0 RC1 and all other plugin are updated too.

**Comment by bassplayer7** [comment] 2015-10-28 14:15
I just spun up a test instance of Grav with AntiMatter, and wasn't able to reproduce the error message. Did you get the exception after sending the email or was it on page load?

The error that you posted in your screenshot isn't helpful anymore as that section of the plugin has been completely reworked.

I did find an unrelated bug, in the process, though. 

Would you be willing to share your User folder so I can test an identical setup? You could put up a Git repo, but just be sure to redact any sensitive information such as passwords, API keys, and the `/accounts` folder.

**Comment by aradianoff** [comment] 2015-10-28 17:00
@umbergerba Sorry for the delay in responding. I am about to give birth any day now so I am currently out of the computer most of the time, I will try to look into it as soon as I can. But, I tried sending an email through your contact form and didn't find any problems... Have you already fixed it?

@bassplayer7 Since the last updates, I have found some issues with the translations and the error and success messages (ex. if you are in Spanish mode it reverts back to English once you try to send a message). I am trying to look into it in detail, but as I said, I am currently out of the computer most of the time and will probably be for the next couple of weeks.
Also, I can't seem to reproduce the problem that made you make the last pull request. Can you give me some more pointers about the problem you encountered?

**Comment by bassplayer7** [comment] 2015-10-28 18:41
@aradianoff, that is certainly a bug. I fixed it and will be pushing the branch and creating a PR for that soon. I don't see how the last updates would have changed that and it looks to me that either a core change affected it or it never worked in the first place - but that's just my observation and I certainly could be wrong.

---

Regarding the other issue, I commented on my PR: #10.

**Comment by Perlkonig** [comment] 2016-09-03 16:24
@bassplayer7 , can we close this now?

**Comment by bassplayer7** [comment] 2016-09-03 17:17
@Perlkonig, I think we should close this, at least unless more details arise regarding this. Since there have been some PRs merged now, there's a good chance that this has been resolved - or at least morphed into something else.

@umbergerba please ping us if this is still an issue for you.

**Closed as completed by bassplayer7** 2016-09-03 17:17 UTC
